name: SevenTX
author: flash1110
version: 1.0
main: me.flash1110.seventx.SevenTX
description: SevenTX plugin coded by Flash

commands:
  clancreate:
    description: Create a clan
    usage: /<command> [name]
  clankick:
    description: Kick someone
    usage: /<command> [player]
  clantag:
    description: Change the tag of a clan
    usage: /<command> [clan] [tag]
  clanjoin:
    description: Join a clan
    usage: /<command> [clan]
  clanleader:
    description: Make someone else the leader
    usage: /<command> [clan] [leader]
  claninvite:
    description: Invite a player
    usage: /<command> [player]

permissions:
  seventx.create:
    description: Create a clan
    default: op